//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interviewplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int interview_id { get; set; }
        public int question_id { get; set; }
        public string answer1 { get; set; }
        public string type { get; set; }
        public string video { get; set; }
        public string audio { get; set; }
    }
}
