//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interviewplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int id { get; set; }
        public int interviewee_id { get; set; }
        public int form_id { get; set; }
        public string uid { get; set; }
    
        public virtual form form { get; set; }
        public virtual interviewee interviewee { get; set; }
    }
}
