//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interviewplus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class interviewplusEntities1 : DbContext
    {
        public interviewplusEntities1()
            : base("name=interviewplusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answer { get; set; }
        public virtual DbSet<app> app { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<form> form { get; set; }
        public virtual DbSet<hr> hr { get; set; }
        public virtual DbSet<interview> interview { get; set; }
        public virtual DbSet<interviewee> interviewee { get; set; }
        public virtual DbSet<question> question { get; set; }
    }
}
