//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interviewplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int id { get; set; }
        public int form_id { get; set; }
        public string settings { get; set; }
        public string app_id { get; set; }
    
        public virtual app app { get; set; }
        public virtual form form { get; set; }
    }
}
